# test java version of library
name: Test Java

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17' # maven won't accept --release argument with java < 8; and 11 is next LTS
      - name: Maven compile
        run: |
            cd java/
            mvn clean compile
      - name: Build with Maven
        env:
          APPENGINE_MAPREDUCE_CI_SERVICE_ACCOUNT_KEY: ${{ secrets.APPENGINE_MAPREDUCE_CI_SERVICE_ACCOUNT_KEY }}
        run: |
          cd java/
          mvn test
