# test java version of library
name: Test Java

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11' # maven won't accept --release argument with java < 8; and 11 is next LTS
      - name: Maven compile
        run: |
            cd java/
            mvn clean compile
      - name: Build with Maven
        run: |
          cd java/
          mvn test