# test java version of library
name: Test Java

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ "com.google.appengine.tools.cloudtasktest.**",
                   "com.google.appengine.tools.mapreduce.impl.**",
                   "com.google.appengine.tools.mapreduce.inputs.**",
                   "com.google.appengine.tools.mapreduce.outputs.**",
                   "com.google.appengine.tools.mapreduce.servlets.**",
                   "com.google.appengine.tools.mapreduce.*Test",
                   "com.google.appengine.tools.pipeline.**" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17' # maven won't accept --release argument with java < 8; and 11 is next LTS
      - id: 'read-cache-maven-packages'
        name: Read Cached Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ env.M2_CACHE_VERSION }}-${{ hashFiles('**/pom.xml') }}
      - name: Maven compile
        run: |
            cd java/
            mvn clean compile
      - id: 'cache-maven-packages'
        name: Cache Maven packages
        uses: actions/cache/save@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ env.M2_CACHE_VERSION }}-${{ hashFiles('**/pom.xml') }}
      - name: Run Tests for Package ${{ matrix.package }}
        env:
          APPENGINE_MAPREDUCE_CI_SERVICE_ACCOUNT_KEY: ${{ secrets.APPENGINE_MAPREDUCE_CI_SERVICE_ACCOUNT_KEY }}
        run: |
          cd java/
          mvn test -Dtest=${{ matrix.package }}